version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Check'
          command: npm run check
      - run:
          name: 'Test'
          command: npm run test
      - run:
          name: 'Push to UXPin'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            ./node_modules/@uxpin/merge-cli/bin/uxpin-merge push
            else
            echo "On '$CIRCLE_BRANCH' branch - not pushing"
            fi
